development:
  adapter: postgresql
  database: charity_infinity_development

test:
  adapter: postgresql
  database: charity_infinity_test

production:
  adapter: postgresql
  database: save_animals_production
  encoding: unicode
  pool: 5
